BK-573 pickup/delivery store desktop
GoodReason-PBDL/goodreasons pull request #18
Opened 2021-02-02 21:09 UTC by jfplataroti

Hey Destin, sorry for this loooong, I think I added more of what this ticket was about. The idea was to add the foundation for the delivery/pickup options for desktop and mobile.

![delivery-pickup-options](https://user-images.githubusercontent.com/1827213/106662821-e2c16600-6570-11eb-8cb1-112ae5178a0a.gif)

## Description

At the top level added two components that add the delivery/pickup options.
* `inlineDeliveryOptions` that shows the `deliveryFields` and `pickupFields` inline.
* `deliveryTabs` that shows `deliveryFields` and `pickupFields` stacked vertically.

Each component was added in a different component because in mobile and desktop the delivery/pickup options are visible in different parts of the page.

The `inlineDeliveryOptions` component was added to the `layout` component so it's visible only for `large` screens.

The `deliveryTabs` component was added to the `menu` page.

**deliveryTabs** uses `Tabs` to allow users select a delivery or pickup option. Base on the selection it shows:
	* `deliveryFields` 
	* `pickupFields`

**InlineDeliveryOptions** uses a button group to allow the user select delivery or pickup. Base on the selection it shows:
	* `deliveryFields`
	* `pickupFields`

**DeliveryFields** renders the `AddessPicker` and `TimePicker` .
Depending on the screen size it will show them inline or stacked.

**PickupFields** renders the `EstablishmentPicker` and `TimePicker` .
Depending on the screen size it will show them inline or stacked.

**TimePicker** depending on the screen it will render the inline version `textField` or the stacked version `modal`.

The subcomponents are organized in the following way:
* modal/ stacked version (mobile)
* textField/ Inline version (desktop)
* `types.ts` contains the props implemented in both subcomponents.

**EstablishmentPicker** depending on the screen it will render the inline version `textField` or the stacked version `modal`.

The subcomponents are organized in the following way:
* modal/ stacked version (mobile)
* textField/ Inline version (desktop)
* `types.ts` contains the props implemented in both subcomponents.

**AddressPicker** depending on the screen it will render the inline version `textField` or the stacked version `modal`.

The subcomponents are organized in the following way:
* modal/ stacked version (mobile)
* textField/ Inline version (desktop)
* `types.ts` contains the props implemented in both subcomponents.

2021-02-03 21:32 UTC, djoyal requested changes
Thanks for this PR! It looks like a lot of thought and effort went into this, which is great! 

Unfortunately it looks like we've ended up with a relatively deep component hierarchy, which makes it difficult to determine what's going on. For example, the `DeliveryFields` component uses the `AddressPicker`, which uses the `AddressModalPicker` -> `AddressFieldModal` -> `AddressField` + `AddressDetails`. It looks like the `onSubmit` function used in `AddressDetails` is actually defined at the top of the dependency chain (in `DeliveryFields`) and then just passed down (with a series of `null` checks at various levels).

Instead of this, it would probably be simpler to just call the `useDeliveryOptions` hook (which is a great hook by the way!) inside of `AddressDetails` and use the `setAddress` function in `AddressDetails` (to avoid having to pass it through all the levels). It'll save a lot of typing, type checking, and make it easier to figure out what `AddressDetails` actually does :)

This pattern seems to be repeated for the `TimePicker` as well (the `setTime` function from the `useDeliveryOptions` hook gets passed all the way down the dependency chain).

Can we remove the unnecessary `index.ts` files? If the module only has 1 export, what benefit do we get from include an `index.ts`? For example, the `deliveryFields` folder only contains two files, the `deliveryFields` component, and an `index.ts` file that exports the `deliveryFields` component. Why not simplify the setup by removing the `index.ts` and moving the `deliveryFields` component to the main `components` folder (so that it is not in the `/deliveryFields` subfolder). Right now there are 6 or 7 `index.ts` files that follow this pattern.

There's a lot happening in this review, so if you want to discuss it please do not hesitate to Slack / call me and we can discuss it offline :)

Again, thanks for putting the work in! The end result looks great, the "behind the scenes" just needs a bit of touching up.

2021-02-03 21:32 UTC, djoyal commented on packages/web/components/addressModal/useAddress.ts
> +      console.log('sdsd', selectedAddress);
Left in by accident?

2021-02-03 21:32 UTC, djoyal commented on packages/web/components/addressModal/useAddress.ts
> +      console.log('eeror', e);
Left in by accident?

2021-02-03 21:32 UTC, djoyal commented on packages/web/components/inlineDeliveryOptions.tsx
> +      <ButtonGroup items={tabs} onClick={onButtonClickHander}></ButtonGroup>
Why use a custom component here instead of `grommet` `Tabs`?

2021-02-03 21:45 UTC, jfplataroti commented
> Thanks for this PR! It looks like a lot of thought and effort went into this, which is great!
> 
> Unfortunately it looks like we've ended up with a relatively deep component hierarchy, which makes it difficult to determine what's going on. For example, the `DeliveryFields` component uses the `AddressPicker`, which uses the `AddressModalPicker` -> `AddressFieldModal` -> `AddressField` + `AddressDetails`. It looks like the `onSubmit` function used in `AddressDetails` is actually defined at the top of the dependency chain (in `DeliveryFields`) and then just passed down (with a series of `null` checks at various levels).
> 
> Instead of this, it would probably be simpler to just call the `useDeliveryOptions` hook (which is a great hook by the way!) inside of `AddressDetails` and use the `setAddress` function in `AddressDetails` (to avoid having to pass it through all the levels). It'll save a lot of typing, type checking, and make it easier to figure out what `AddressDetails` actually does :)
> 
> This pattern seems to be repeated for the `TimePicker` as well (the `setTime` function from the `useDeliveryOptions` hook gets passed all the way down the dependency chain).
> 
> Can we remove the unnecessary `index.ts` files? If the module only has 1 export, what benefit do we get from include an `index.ts`? For example, the `deliveryFields` folder only contains two files, the `deliveryFields` component, and an `index.ts` file that exports the `deliveryFields` component. Why not simplify the setup by removing the `index.ts` and moving the `deliveryFields` component to the main `components` folder (so that it is not in the `/deliveryFields` subfolder). Right now there are 6 or 7 `index.ts` files that follow this pattern.
> 
> There's a lot happening in this review, so if you want to discuss it please do not hesitate to Slack / call me and we can discuss it offline :)
> 
> Again, thanks for putting the work in! The end result looks great, the "behind the scenes" just needs a bit of touching up.

hey, thanks for taking the time to an analysis of the hierarchy! :) 

Initially, I wanted just to connect the top-level component to the hooks and the child components (the pickers) to communicate through the props but I ended up making things a bit more complicated hehe.

I like the suggestions of removing some files and simplifying the communication between the parent component and child component with the hook.

I'll start with some of the changes but If it's ok I'll schedule some minutes tomorrow to chat and discuss the options.

2021-02-03 21:46 UTC, jfplataroti commented on packages/web/components/inlineDeliveryOptions.tsx
> +      <ButtonGroup items={tabs} onClick={onButtonClickHander}></ButtonGroup>
I tried but in this case, the content needs to be rendered at the same line of the tabs.

If it's possible of course I'll change it to the grommet tabs.

2021-02-03 21:46 UTC, jfplataroti commented on packages/web/components/addressModal/useAddress.ts
> +      console.log('eeror', e);
yes thanks

2021-02-03 21:46 UTC, jfplataroti commented on packages/web/components/addressModal/useAddress.ts
> +      console.log('sdsd', selectedAddress);
yes thanks

2021-02-03 21:49 UTC, jfplataroti commented on packages/web/hooks/useDesktopLayout.tsx
> +export default function useDesktopSize() {
I ended up adding a new hook because `useMobileLayout` is used when the size is `small` and `xsmall` and on desktop, I wanted to be sure the size of the screen is `large`.

Maybe instead of useDesktopSize it can be called `useSize` with the expected size as a param?

2021-02-03 21:53 UTC, jfplataroti commented on packages/web/hooks/useEstablishments.ts
> +    CompanyService.GetNearestEstablishments(location)
good point. Yes at the moment when the API gets no location it just returns the list (of the only location).

Having an address search bar could be a nice feature.

2021-02-03 21:55 UTC, jfplataroti commented on packages/web/components/deliveryFields/deliveryFields.tsx
> +  const isDesktop = useDesktopSize();
same as above needed size `large` to switch between layouts. (open to discussion :) )

2021-02-03 21:55 UTC, jfplataroti commented on packages/web/pages/establishment/[establishmentId]/menu.tsx
> +      {!isDesktop && <DeliveryTabs />}
same as above needed size `large` to switch between layouts. (open to discussion :) )

2021-02-03 23:50 UTC, djoyal commented on packages/web/components/inlineDeliveryOptions.tsx
> +      <ButtonGroup items={tabs} onClick={onButtonClickHander}></ButtonGroup>
Oh, sorry - I thought this was for the mobile layout for some reason. I think a `RadioButtonGroup` might be able to accomplish this though (without needing a custom component). We're able to apply a custom styling to the radio buttons (see the `Checkout` page's `Delivery Options` for an example)

2021-02-03 23:54 UTC, djoyal commented on packages/web/hooks/useDesktopLayout.tsx
> +export default function useDesktopSize() {
> `useMobileLayout` is used when the size is `small` and `xsmall`

Right, so it returns `true` when a mobile device is used, and `false` when a desktop size (`medium`, `large`, or `xlarge`) is detected. 

> Maybe instead of useDesktopSize it can be called `useSize` with the expected size as a param?

That's an option, but seeing as we're only targeting two sizes (`Mobile` and `Desktop`) I don't think we necessarily need that level of granularity (I don't think Design will want to create different layouts for each of the 5 sizes available in `grommet`)

2021-02-04 02:46 UTC, jfplataroti commented on packages/web/components/inlineDeliveryOptions.tsx
> +      <ButtonGroup items={tabs} onClick={onButtonClickHander}></ButtonGroup>
nice! yeah that would be much better. 👍

2021-02-05 15:06 UTC, closed without merging

2021-02-05 15:07 UTC, jfplataroti commented
Closed, this PR will be delivered with the feedback suggested in smaller PRs :)